### ISSUE TITLE
Stuck "Starting tmate"

### ISSUE THREAD

**Issue by dlapiduz** [cloudfoundry-community/cf-ssh#2]
I started a `cf-ssh` instance but it keeps getting stuck on `Starting tmate...`.

Do you have any ideas of what it could be?

**Comment by scotttag** [comment]
Are you getting a timeout on the tmate connection? If so - you need to check that your running-bound security groups in CF allow internet traffic (or at least traffic to the tmate server) - and that your firewalls allow the same

**Comment by davehodg** [comment]
Usually strace is my friend in this situation. You'll see what the program is doing when it got stuck...
