### ISSUE TITLE
Permission denied (publickey) on windows64

### ISSUE THREAD

**Issue by dzlab** [cloudfoundry-community/cf-ssh#4]
I'm trying to run cf-ssh (release: `cf-ssh_windows_amd64`) from a windows 7 machine. I'm running from admin console, I get the following error:

```
$ cf-ssh -f manifest.yml
Deploying SSH container 'osmoze-ssh'...
Initiating tmate connection...success
The authenticity of host 'am.tmate.io (82.196.12.126)' can't be established.
RSA key fingerprint is af:2d:81:c1:fe:49:70:2d:7f:09:a9:d7:4b:32:e3:be.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'am.tmate.io,82.196.12.126' (RSA) to the list of known hosts.
Permission denied (publickey).
```

When I check the running apps, I can see 'osmoze-ssh':

```
$ cf apps
Getting apps in org heavenize / space dev as admin...
OK

name         requested state   instances   memory   disk   urls
osmoze-ssh   started           1/1         2G       1G
osmoze       stopped           0/1         2G       1G     osmoze-phototactic-cylinder.10.244.0.34.xip.io
```

My app 'osmoze' originally [failed](https://groups.google.com/a/cloudfoundry.org/forum/#!topic/bosh-users/cUrHEg7zBYg) and I'm trying to find the failure problem.
Any idea what's worng, why I'm getting `Permission denied (publickey)` and how to fix it?

**Comment by TheJKFever** [comment]
I'm having this same problem, but I'm using an ubuntu machine and the cf-ssh_linux_amd64 release.
