### ISSUE TITLE
Add missing license information for this project

### ISSUE THREAD

**Issue by brittag** [cloudfoundry-community/cf-ssh#9]
While working on updating documentation for [my team's fork of cf-ssh](https://github.com/18F/cf-ssh), I looked for a license statement in this repository so that I could include that information in our fork, and I couldn't find license information here. I'd like to provide a note in our fork about the open source license of this work (and our team's modifications) so that other people can feel fully welcome to reuse/adapt our fork if they like.

@drnic, as the main author, would you consider adding a note to this readme (or a license file) to indicate the license you'd like this to be under?

Thank you!

**Comment by drnic** [comment]
Thanks for the prompt. Done.
